### ISSUE TITLE
doesn't play songs within emacs

### ISSUE THREAD

**Issue by 3marcusw** [dochang/emms-player-mpv#4]
When playing certain files, like m4a files, mpv "escapes" emacs and it plays in its own separate window and is problematic.
However, when i edit emms-player-mpv.el to also pass "--no-video" to mpv, this fixes the problem. For example:
```
(define-emms-simple-player mpv '(file url streamlist playlist)
  (concat "\\`\\(http\\|mms\\)://\\|"
          (emms-player-simple-regexp
           "ogg" "mp3" "wav" "mpg" "mpeg" "wmv" "wma"
           "mov" "avi" "divx" "ogm" "ogv" "asf" "mkv"
           "rm" "rmvb" "mp4" "flac" "vob" "m4a" "ape"
           "flv" "webm"))
  "mpv" "--quiet" "--really-quiet" "--no-video")
```
Mac OS X 10.9 Mavericks
EMMS 4.0
Emacs 24.4

**Comment by alezost** [comment]
I'm not sure I understand what you mean, but if you don't like that mpv
shows an embedded image, you can disable it by putting
`audio-display=no` in your mpv config.  It is suggested by @rynffoll
(thanks for that btw :+1:) at https://github.com/dochang/emms-player-mpv/pull/3.

And I can only repeat that I'm against using `--no-video` as a default
option, because there might be people (including me) who use EMMS+mpv to
watch videos.

**Comment by 3marcusw** [comment]
thanks
